apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "20M"
spec:
  tls:
    - hosts:
        - "4sh-formation-@ENV.quatre.app"
      secretName: my-training-@ENV-cert
  rules:
    - host: 4sh-formation-@ENV.quatre.app
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: app-srv
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-ui
                port:
                  number: 80
---
