apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 4sh-formation-@ME
resources:
  - ../../base
configMapGenerator:
  - name: env-config
    envs:
      - env.conf
  - name: app-config
    files:
      - app.conf
images:
  - name: europe-docker.pkg.dev/quatreapp/k8straining/myapp-ui-me
    newName: europe-docker.pkg.dev/quatreapp/k8straining/myapp-ui-@ME:1.0
  - name: europe-docker.pkg.dev/quatreapp/k8straining/myapp-srv-me
    newName: europe-docker.pkg.dev/quatreapp/k8straining/myapp-srv-@ME:2.0.0