apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 4sh-formation-@ME
resources:
  - ../../base
configMapGenerator:
  - name: app-config
    envs:
      - application.conf
patches:
  - path: patches/ingress.patch.json
    target:
      kind: Ingress
      name: ingress
  - path: patches/srv.patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      labelSelector: app=app-srv
images:
  - name: europe-west9-docker.pkg.dev/qsh-learning/qsh-learning-docker-registry/myapp-ui-me
    newName: europe-west9-docker.pkg.dev/qsh-learning/qsh-learning-docker-registry/myapp-ui-@ME
  - name: europe-west9-docker.pkg.dev/qsh-learning/qsh-learning-docker-registry/myapp-srv-me
    newName: europe-west9-docker.pkg.dev/qsh-learning/qsh-learning-docker-registry/myapp-srv-@ME
